baseurl = "http://smart-dating.online/personality/"
title = "Smart Dating"
copyright = "Copyright (c) 2008 - 2014, all rights reserved."
languageCode = "en-US"
canonifyurls = true
paginate = 3
theme = "hugo-dusk"
publishDir = "../docs/personality"


googleAnalytics = ""
disqusShortname = ""

#SectionPagesMenu = "main"

[[menu.main]]
  name = "Home"
  weight = -120
  identifier = "home"
  url = "../"

  
[author]
  name = ""

[params.meta]
  keywords = ""
  description = "Personal blog."

[params]
  #email = "myemail"
  #github = "github id"
  #gitlab = "gitlab id"
  #twitter = "twitter id"
  #linkedin = "linkedin id"
  facebook = "facebookid"
